In [2]:
import pandas as pd

In [30]:
import numpy as np

In [14]:
good_files = ['00/1164200.mp3',
 '00/12100.mp3',
 '00/1295900.mp3',
 '00/985000.mp3',
 '00/1398500.mp3',
 '00/1210700.mp3',
 '00/818600.mp3',
 '00/1339600.mp3',
 '00/506100.mp3',
 '00/390000.mp3',
 '00/16000.mp3',
 '00/1052800.mp3',
 '00/699100.mp3']

In [4]:
MOODPATH = "/mnt/c/Users/aag12/Downloads/autotagging_moodtheme.tsv.txt"

In [5]:
with open(MOODPATH, 'r') as f:
    moodraw = f.read()

In [9]:
col_names = ['TRACK_ID',
 'ARTIST_ID',
 'ALBUM_ID',
 'PATH',
 'DURATION',
 'TAGS',
 'TAGS2',
 'TAGS3',
 'TAGS4',
 'TAGS5',
 'TAGS6',
 'TAGS7',
 'TAGS8',
 'TAGS9']

In [20]:
df = pd.read_csv(MOODPATH, sep='\t', names=col_names)

In [21]:
# df["PATH"] = [p.replace(".mp3", ".npy") for p in df["PATH"].values]

In [97]:
df = df[df["PATH"].isin(good_files)]

In [55]:
# num_seen = 0
# for t in set(track_ids):
#     if t in moodraw:
#         num_seen += 1

In [56]:
num_moods = 15

In [57]:
inds ={'fast': 0,
 'sexy': 1,
 'mellow': 2,
 'heavy': 3,
 'horror': 4,
 'travel': 5,
 'holiday': 6,
 'groovy': 7,
 'funny': 8,
 'retro': 9,
 'hopeful': 10,
 'powerful': 11,
 'cool': 12,
 'nature': 13,
 'game': 14}

In [58]:
len(inds)

15

In [59]:
def sudo_one_hot(df, inds):
#     mini_df = df[df['PATH'].isin(soi)]
    final = []
    for i in range(len(df)):
        curr = np.zeros(len(inds))
        moods = list(df.iloc[i])[5:]
        for theme in moods:
            if type(theme) == str and "mood" in theme:
                check = theme.split("---")[-1]
                if check in inds:
                    curr[inds[check]] = 1
                else:
                    break
        final.append(curr)
    return final

In [74]:
moods

['mood/theme---christmas',
 'mood/theme---holiday',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [75]:
df.iloc[i]

TRACK_ID              track_1398500
ARTIST_ID             artist_439371
ALBUM_ID               album_163742
PATH                 00/1398500.mp3
DURATION                      166.7
TAGS         mood/theme---christmas
TAGS2          mood/theme---holiday
TAGS3                           NaN
TAGS4                           NaN
TAGS5                           NaN
TAGS6                           NaN
TAGS7                           NaN
TAGS8                           NaN
TAGS9                           NaN
Name: 17530, dtype: object

In [88]:
final = []
for i in range(len(df)):
    curr = np.zeros(len(inds))
    moods = list(df.iloc[i])[5:]
    for theme in moods:
        if type(theme) == str and "mood" in theme:
            check = theme.split("---")[-1]
            if check in inds:
                curr[inds[check]] = 1
        else:
            pass
        
    final.append(curr)

In [89]:
curr

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
curr

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [91]:
moods

['mood/theme---christmas',
 'mood/theme---holiday',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [92]:
len(inds)

15

In [96]:
final

[array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])]

In [93]:
inds

{'fast': 0,
 'sexy': 1,
 'mellow': 2,
 'heavy': 3,
 'horror': 4,
 'travel': 5,
 'holiday': 6,
 'groovy': 7,
 'funny': 8,
 'retro': 9,
 'hopeful': 10,
 'powerful': 11,
 'cool': 12,
 'nature': 13,
 'game': 14}

In [95]:
# sudo_one_hot(df, inds)
